-- ═══════════════════════════════════════════════════════════════
-- CFI MIGRATION — Enrich cfi_mills_60tph with GFW GPS + RSPO
-- Run date: March 17 2026
-- Source: GFW Universal Mill List v20220531 (shapefile)
-- Method: Python rapidfuzz token_sort_ratio matching on mill name
--         within same province. HIGH = score ≥80, MEDIUM = 60–79.
-- Result: 40 of 105 mills now have GPS, district, verified RSPO.
--         65 remaining have generic placeholder names — no GFW match possible.
-- ═══════════════════════════════════════════════════════════════

-- Run in a FRESH Supabase SQL Editor tab

UPDATE cfi_mills_60tph SET latitude = 0.809088, longitude = 101.277952, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Kampar', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BINA FITRI JAYA (score=100, HIGH) uml_id=PO1000004419' WHERE mill_name = 'Bina Fitri Jaya' AND owner_company = 'Anglo-Eastern Plantations';
UPDATE cfi_mills_60tph SET latitude = 0.809088, longitude = 101.277952, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Kampar', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BINA FITRI JAYA (score=94, HIGH) uml_id=PO1000004419' WHERE mill_name = 'Bina Fitri Jaya 2' AND owner_company = 'Anglo-Eastern Plantations';
UPDATE cfi_mills_60tph SET latitude = 0.434444, longitude = 101.825, rspo_status = 'RSPO Certified', district_kabupaten = 'Siak', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BUATAN I (score=86, HIGH) uml_id=PO1000000021' WHERE mill_name = 'Asian Agri PKS Buatan' AND owner_company = 'Asian Agri';
UPDATE cfi_mills_60tph SET latitude = 2.002806, longitude = 100.243611, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu Selatan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TELUK PANJIE (score=96, HIGH) uml_id=PO1000002146' WHERE mill_name = 'Asian Agri PKS Teluk Panji' AND owner_company = 'Asian Agri';
UPDATE cfi_mills_60tph SET latitude = -2.483162, longitude = 111.018391, rspo_status = 'RSPO Certified', district_kabupaten = 'Ketapang', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: MANIS MATA (score=100, HIGH) uml_id=PO1000001208' WHERE mill_name = 'AAL PKS Manis Mata' AND owner_company = 'Astra Agro Lestari';
UPDATE cfi_mills_60tph SET latitude = -1.439331, longitude = 116.399383, rspo_status = 'RSPO Certified', district_kabupaten = 'Penajam Paser Utara', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: PKS PASER (score=71, MEDIUM) uml_id=PO1000008623' WHERE mill_name = 'AAL PKS Paser' AND owner_company = 'Astra Agro Lestari';
UPDATE cfi_mills_60tph SET latitude = -2.433267, longitude = 110.817511, rspo_status = 'RSPO Certified', district_kabupaten = 'Ketapang', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: PAKU JUANG (score=67, MEDIUM) uml_id=PO1000001207' WHERE mill_name = 'Cargill PKS Paku Juang (Harapan)' AND owner_company = 'Cargill Tropical Palm';
UPDATE cfi_mills_60tph SET latitude = -2.514533, longitude = 110.914703, rspo_status = 'RSPO Certified', district_kabupaten = 'Ketapang', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: RIVER VIEW (score=67, MEDIUM) uml_id=PO1000002360' WHERE mill_name = 'Cargill PKS River View (Harapan)' AND owner_company = 'Cargill Tropical Palm';
UPDATE cfi_mills_60tph SET latitude = -2.612778, longitude = 104.128242, rspo_status = 'RSPO Certified', district_kabupaten = 'Musi Banyuasin', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SUNGAI LILIN (score=71, MEDIUM) uml_id=PO1000000058' WHERE mill_name = 'Cargill PKS Sungai Lilin (Hindoli)' AND owner_company = 'Cargill Tropical Palm';
UPDATE cfi_mills_60tph SET latitude = -2.5496, longitude = 103.944, rspo_status = 'RSPO Certified', district_kabupaten = 'Musi Banyuasin', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TANJUNG DALAM (score=72, MEDIUM) uml_id=PO1000009068' WHERE mill_name = 'Cargill PKS Tanjung Dalam (Hindoli)' AND owner_company = 'Cargill Tropical Palm';
UPDATE cfi_mills_60tph SET latitude = -0.875633, longitude = 115.891653, rspo_status = 'RSPO Certified', district_kabupaten = 'Kutai Barat', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: KETAPANG AGRO LESTARI (score=100, HIGH) uml_id=PO1000008567' WHERE mill_name = 'FR PKS Ketapang Agro Lestari' AND owner_company = 'First Resources';
UPDATE cfi_mills_60tph SET latitude = -1.082883, longitude = 110.38345, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Kayong Utara', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SWADAYA MUKTI PRAKARSA (score=100, HIGH) uml_id=PO1000004436' WHERE mill_name = 'FR PKS Swadaya Mukti Prakarsa' AND owner_company = 'First Resources';
UPDATE cfi_mills_60tph SET latitude = -3.461533, longitude = 135.256064, rspo_status = 'RSPO Certified', district_kabupaten = 'Nabire', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: NABIRE MATOA (score=83, HIGH) uml_id=PO1000011406' WHERE mill_name = 'Goodhope Nabire Matoa Mill' AND owner_company = 'Goodhope Asia Holdings';
UPDATE cfi_mills_60tph SET latitude = -2.524252, longitude = 112.4168, rspo_status = 'RSPO Certified', district_kabupaten = 'Seruyan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SUNGAI PURUN (score=83, HIGH) uml_id=PO1000002676' WHERE mill_name = 'Goodhope Sungai Purun Mill' AND owner_company = 'Goodhope Asia Holdings';
UPDATE cfi_mills_60tph SET latitude = -2.559957, longitude = 112.3736, rspo_status = 'RSPO Certified', district_kabupaten = 'Seruyan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TERAWAN (score=74, MEDIUM) uml_id=PO1000002677' WHERE mill_name = 'Goodhope Terawan Mill' AND owner_company = 'Goodhope Asia Holdings';
UPDATE cfi_mills_60tph SET latitude = 3.479046, longitude = 98.267726, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Langkat', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TURANGIE (score=100, HIGH) uml_id=PO1000002367' WHERE mill_name = 'Lonsum PKS Turangie' AND owner_company = 'London Sumatra (Lonsum)';
UPDATE cfi_mills_60tph SET latitude = 0.077043, longitude = 102.030838, rspo_status = 'RSPO Certified', district_kabupaten = 'Pelalawan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BATANG KULIM (score=100, HIGH) uml_id=PO1000000054' WHERE mill_name = 'Musim Mas PKS Batang Kulim' AND owner_company = 'Musim Mas';
UPDATE cfi_mills_60tph SET latitude = 2.1, longitude = 99.77, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SIRINGO RINGO (score=77, MEDIUM) uml_id=PO1000001529' WHERE mill_name = 'Musim Mas PKS Siringo-Ringo' AND owner_company = 'Musim Mas';
UPDATE cfi_mills_60tph SET latitude = 1.999722, longitude = 99.939722, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: AEK NABARA (score=100, HIGH) uml_id=PO1000002145' WHERE mill_name = 'PTPN III PKS Aek Nabara' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 1.79278, longitude = 100.15583, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu Selatan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: AEK TOROP (score=100, HIGH) uml_id=PO1000001565' WHERE mill_name = 'PTPN III PKS Aek Torop' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 3.120417, longitude = 99.159067, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Simalungun', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: DOLOK ILIR (score=100, HIGH) uml_id=PO1000002539' WHERE mill_name = 'PTPN III PKS Dolok Ilir' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 3.526085, longitude = 98.89842, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Deli Serdang', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: PAGAR MERBAU (score=100, HIGH) uml_id=PO1000004944' WHERE mill_name = 'PTPN III PKS Pagar Merbau' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 3.351006, longitude = 99.169742, rspo_status = 'RSPO Certified', district_kabupaten = 'Serdang Bedagai', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: RAMBUTAN (score=100, HIGH) uml_id=PO1000004342' WHERE mill_name = 'PTPN III PKS Rambutan' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 3.13077, longitude = 99.343861, rspo_status = 'RSPO Certified', district_kabupaten = 'Simalungun', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SEI MANGKEI (score=100, HIGH) uml_id=PO1000000879' WHERE mill_name = 'PTPN III PKS Sei Mangkei' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 2.90205, longitude = 99.5094, rspo_status = 'RSPO Certified', district_kabupaten = 'Asahan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SEI SILAU (score=100, HIGH) uml_id=PO1000004948' WHERE mill_name = 'PTPN III PKS Sei Silau' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 1.709217, longitude = 100.289067, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu Selatan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TORGAMBA (score=100, HIGH) uml_id=PO1000004929' WHERE mill_name = 'PTPN III PKS Torgamba' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 3.568533, longitude = 98.94805, rspo_status = 'RSPO Certified', district_kabupaten = 'Serdang Bedagai', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: ADOLINA (score=100, HIGH) uml_id=PO1000004497' WHERE mill_name = 'PTPN IV PKS Adolina' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 0.546917, longitude = 101.2291, rspo_status = 'RSPO Certified', district_kabupaten = 'Kampar', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SUNGAI GALUH (score=76, MEDIUM) uml_id=PO1000007604' WHERE mill_name = 'PTPN V PKS Sei Galuh' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 0.599154, longitude = 100.69283, rspo_status = 'RSPO Certified', district_kabupaten = 'Kampar', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: TANDUN (score=100, HIGH) uml_id=PO1000004402' WHERE mill_name = 'PTPN V PKS Tandun' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 0.250556, longitude = 110.303889, rspo_status = 'Not RSPO Certified', district_kabupaten = 'Sanggau', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: PARINDU (score=100, HIGH) uml_id=PO1000008159' WHERE mill_name = 'PTPN XIII PKS Parindu' AND owner_company = 'PTPN III (PalmCo)';
UPDATE cfi_mills_60tph SET latitude = 2.2114, longitude = 117.165867, rspo_status = 'RSPO Certified', district_kabupaten = 'Berau', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BERAU (score=100, HIGH) uml_id=PO1000004533' WHERE mill_name = 'GAR PKS Berau' AND owner_company = 'Sinar Mas / SMART (GAR)';
UPDATE cfi_mills_60tph SET latitude = 0.928611, longitude = 101.206389, rspo_status = 'RSPO Certified', district_kabupaten = 'Siak', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: LIBO (score=100, HIGH) uml_id=PO1000001057' WHERE mill_name = 'GAR PKS Libo' AND owner_company = 'Sinar Mas / SMART (GAR)';
UPDATE cfi_mills_60tph SET latitude = -2.100833, longitude = 102.374444, rspo_status = 'RSPO Certified', district_kabupaten = 'Merangin', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: LANGLING (score=62, MEDIUM) uml_id=PO1000001345' WHERE mill_name = 'GAR PKS Merangin' AND owner_company = 'Sinar Mas / SMART (GAR)';
UPDATE cfi_mills_60tph SET latitude = 0.9375, longitude = 101.3002, rspo_status = 'RSPO Certified', district_kabupaten = 'Siak', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: SAM-SAM (score=92, HIGH) uml_id=PO1000001058' WHERE mill_name = 'GAR PKS Samsam' AND owner_company = 'Sinar Mas / SMART (GAR)';
UPDATE cfi_mills_60tph SET latitude = -0.2232, longitude = 102.095, rspo_status = 'RSPO Certified', district_kabupaten = 'Pelalawan', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: UKUI I (score=80, HIGH) uml_id=PO1000000148' WHERE mill_name = 'GAR PKS Ukui' AND owner_company = 'Sinar Mas / SMART (GAR)';
UPDATE cfi_mills_60tph SET latitude = -0.598056, longitude = 102.983333, rspo_status = 'RSPO Certified', district_kabupaten = 'Indragiri Hilir', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BUMI PALMA (score=100, HIGH) uml_id=PO1000001064' WHERE mill_name = 'Wilmar PKS Bumi Palma' AND owner_company = 'Wilmar International';
UPDATE cfi_mills_60tph SET latitude = -0.022183, longitude = 109.424883, rspo_status = 'RSPO Certified', district_kabupaten = 'Kubu Raya', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BUMI PRATAMA KHATULISTIWA (score=100, HIGH) uml_id=PO1000004335' WHERE mill_name = 'Wilmar PKS Bumi Pratama Khatulistiwa' AND owner_company = 'Wilmar International';
UPDATE cfi_mills_60tph SET latitude = -2.230183, longitude = 112.49125, rspo_status = 'RSPO Certified', district_kabupaten = 'Kotawaringin Timur', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: BUMI SAWIT KENCANA (score=100, HIGH) uml_id=PO1000001043' WHERE mill_name = 'Wilmar PKS Bumi Sawit Kencana' AND owner_company = 'Wilmar International';
UPDATE cfi_mills_60tph SET latitude = 2.286111, longitude = 100.140833, rspo_status = 'RSPO Certified', district_kabupaten = 'Labuhanbatu', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: DAYA LABUHAN INDAH 2 (score=95, HIGH) uml_id=PO1000002132' WHERE mill_name = 'Wilmar PKS Daya Labuhan Indah' AND owner_company = 'Wilmar International';
UPDATE cfi_mills_60tph SET latitude = 1.561111, longitude = 100.541667, rspo_status = 'RSPO Certified', district_kabupaten = 'Rokan Hilir', cfi_notes = COALESCE(cfi_notes, '') || ' | GFW match: ALUR DUMAI (score=67, MEDIUM) uml_id=PO1000000326' WHERE mill_name = 'Wilmar PKS Dumai' AND owner_company = 'Wilmar International';

-- VERIFY
SELECT COUNT(*) AS total,
       COUNT(CASE WHEN latitude IS NOT NULL THEN 1 END) AS has_gps,
       COUNT(CASE WHEN rspo_status = 'RSPO Certified' THEN 1 END) AS rspo_certified
FROM cfi_mills_60tph;
-- Expected: total=105, has_gps=40, rspo_certified=33
